version: '3.9'
services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-pass
      MYSQL_USER: dalean
      MYSQL_PASSWORD: my-pass
    ports:
      - 3306:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./MYSQL/database:/var/lib/mysql:rw
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080